#########################################
### System-Api configuration          ###
#########################################
metricsConfig:
  monitor:
    interval: 45
    unit: SECONDS
  history:
    interval: 30
    unit: MINUTES
    purging:
      olderThan: 14
      unit: DAYS
      purgeEvery: 1
      purgeEveryUnit: DAYS
  cache:
    enabled: true
    duration: 5
    unit: SECONDS
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
  eventLog:
    enabled: true
  serviceManagement:
    enabled: true
linux:
  journalLogs:
    enabled: true
  systemDaemonServiceManagement:
    enabled: true
# web interface for running queries
graphQLPlayGround:
  enabled: true
# docker management and metrics support
docker:
  enabled: true
# resolve external IP and monitor internet connectivity
connectivityCheck:
  enabled: true
  address: https://ifconfig.me
updateCheck:
  enabled: true
  address: https://api.github.com
  user: krillsson
  repo: sys-api
# advertise service in local network for easier client setup
mDNS:
  enabled: true
upnp:
  enabled: true
forwardHttpToHttps: false
selfSignedCertificates:
  enabled: true
  ## automatically put external IP in CN
  populateCN: true
  ## automatically put internal IPs in SAN
  populateSAN: true
  ## manually populate CN and SAN below
  # commonName: sys-api.org
  # subjectAlternativeNames: [192.168.0.24, 10.8.0.24]
tasks:
  often:
    interval: 5s
    perform: [ RecordCpuLoad, RecordDiskReadWriteRate, RecordNetworkUploadDownloadRate ]
  lessOften:
    interval: 15s
    perform: [ UpdateProcessesList, CheckMonitors ]
  seldom:
    interval: 5min
    perform: [ CheckConnectivity ]
  verySeldom:
    interval: 30min
    perform: [ StoreMetricHistoryEntry ]
logReader:
  files:
    - /var/log/nginx/access.log
  directories:
    - data
    - /var/log
#########################################
### Dropwizard specific configuration ###
#########################################
graphql:
  enableTracing: false
  queryCache: maximumSize=10000
  schemaFiles:
    - schema.graphqls

server:
  maxThreads: 100
  minThreads: 1
  maxQueuedRequests: 100
  idleThreadTimeout: 1 minute
  rootPath: /api/
  adminContextPath: /admin
  applicationContextPath: /
  requestLog:
    appenders:
      - type: file
        threshold: INFO
        currentLogFilename: data/request.log
        archivedLogFilenamePattern: data/request-%d{yyyy-MM-dd}-%i.log
        archivedFileCount: 3
        timeZone: UTC
        maxFileSize: 2MiB
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: data/keystorewww.jks
      keyStorePassword: sys-api
      certAlias: sys-api-key
      validateCerts: false
      validatePeers: false
logging:
  # The default level of all loggers.
  # Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    com.krillsson.sysapi: DEBUG
    oshi: INFO
    io.dropwizard.core.server.ServerFactory: INFO
    io.dropwizard.core.setup.AdminEnvironment: OFF
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: '%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg%n'
      currentLogFilename: data/application.log
      archivedLogFilenamePattern: data/application-%d{yyyy-MM-dd}-%i.log
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 2MiB