version: "3"
services:
  sys-api:
    container_name: sys-api
    # krillsson/sys-api:native to try the native build
    image: krillsson/sys-api:latest
    # exposes NIC's for sys-API to read
    network_mode: host
    cap_add:
      - SYS_RAWIO
    # Uncomment if you don't want to run in network_mode: host
    # ports:
    # - "8080:8080"
    # - "8443:8443"
    #  # port for docker management API.
    # - "2375:2375"
    # expose host processes for container.
    pid: "host"
    volumes:
      # change "/path/to/*" point to a directory on your machine
      - /path/to/data:/data
      - /path/to/config:/config
      # socket for docker management API.
      - /var/run/docker.sock:/var/run/docker.sock
      # to read device names from disks
      - /run/udev:/run/udev:ro
      # to control systemd
      - /run/systemd:/run/systemd
      # to read journal logs
      - /etc/machine-id:/etc/machine-id:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro
      - /run/log/journal:/run/log/journal:ro
      # to allow sys-API access to read info about disks
      - /dev:/dev:ro
      # show correct os info in about server screen
      - /etc/os-release:/etc/os-release
    # temperature monitoring of disks
    #devices:
    #  - "/dev/sda:/dev/sda"
    restart: unless-stopped