name: Build nightly Docker images
run-name: Build and push nightly native and jvm images to Docker Hub

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build nightly sys-API distributions
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Upload JVM build to Docker Hub
        run: ./gradlew jibJvm
      - name: Upload Graal native build to Docker Hub
        run: ./gradlew jibNativeImage
      - name: Build shadowJar
        run: ./gradlew shadowDistZip
      - name: Build .deb
        run: ./gradlew packageDeb
      - name: Store distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-dist
          path: build/distributions/*.zip
      - name: Store .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: sys-api-debian-package
          path: build/distributions/*.deb
      - name: Store native image artifact
        uses: actions/upload-artifact@v4
        with:
          name: sys-api-native-image
          path: build/native/nativeCompile/sysapi
# Disabled due to https://github.com/pwall2222/inno-setup-download/issues/1
#  build-win:
#    name: Build nightly on Windows
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: inno-setup-download
#        uses: pwall2222/inno-setup-download@v0.0.4
#      - name: Set Up JDK
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: 'gradle'
#      - name: Build Windows installer
#        run: ./gradlew packageWindowsInstaller
#      - name: Store setup.exe artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows-setup
#          path: build/*.exe