name: Build nightly Docker images
run-name: Build and push nightly native and jvm images to Docker Hub
on: [ push ]
jobs:
  build:
    name: Build nightly container
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Upload JVM build to Docker Hub
        run: ./gradlew jibJvm
      - name: Upload Graal native build to Docker Hub
        run: ./gradlew jibNativeImage