name: Native docker image
run-name: Build and push native image to Docker Hub
on: [ push ]
jobs:
  build:
    name: Build nightly container
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Compile native image
        run: gradlew nativeCompile
      - name: Upload using jib
        run: gradlew jib