name: Build Docker images
run-name: Build and push native and jvm images to Docker Hub
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build container
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Upload JVM build to Docker Hub
        run: ./gradlew jibJvm -PbuildType="release"
      - name: Upload Graal native build to Docker Hub
        run: ./gradlew jibNativeImage -PbuildType="release"
      - name: Build shadowJar
        run: ./gradlew shadowDistZip
      - name: Store distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: Store distribution zip file
          path: build/distributions/*.zip
      - name: Store native image artifact
        uses: actions/upload-artifact@v4
        with:
          name: Store native image
          path: build/native/nativeCompile/sysapi
