name: Build Docker images
run-name: Build and push native and jvm images to Docker Hub
on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-docker:
    name: Build sys-API docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Upload JVM build to Docker Hub
        run: ./gradlew jibJvm -PbuildType="release" -PsemVerTag="${{  github.ref_name }}"
      - name: Build shadowJar
        run: ./gradlew shadowDistZip
      - name: Store distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-dist
          path: build/distributions/*.zip
  build-deb:
    name: Build sys-API debian package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Build .deb
        run: ./gradlew packageDeb
      - name: Store .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: sys-api-debian-package
          path: build/distributions/*.deb
  build-cmd:
    name: Build sys-API commandline .zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Build shadowJar
        run: ./gradlew shadowDistZip
      - name: Store distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadow-dist
          path: build/distributions/*.zip
  build-win:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: inno-setup-download
        uses: pwall2222/inno-setup-download@v0.0.6
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build Windows installer
        run: ./gradlew packageWindowsInstaller
      - name: Store setup.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-setup
          path: build/*.exe
  build-docker-native:
    name: Build GraalVM sys-API distribution
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'
      - name: Upload Graal native build to Docker Hub
        run: ./gradlew jibNativeImage -PbuildType="release" -PsemVerTag="${{  github.ref_name }}"
      - name: Store native image artifact
        uses: actions/upload-artifact@v4
        with:
          name: sys-api-native-image
          path: build/native/nativeCompile/sysapi